### ISSUE TITLE
Is it possible to add an XSL/customize the output?

### ISSUE THREAD

**Issue by fatso83** [Geta/SEO.Sitemaps#36]
It's usually possible to add a stylesheet to an xml document ([like this](https://www.xml-sitemaps.com/sitemap.xml)) to present a friendlier output to browsers. Is is possible to do this using this plugin? This might touch upon #35, as it might make sense to [extend the sitemap protocol](http://www.sitemaps.org/protocol.html#extending) with custom elements for this purpose (such as a title for the link).

**Comment by fatso83** [comment]
I thought I might add some pointers for late comers on how to work around this.

For our part, a HTML sitemap was needed SEO optimization. As this basically was a slightly different output than the XML this plugin generated, I wondered if one could customize the output format, hence #35 and this issue.

The workaround I implemented was strictly outside of this:
- add a route for `/sitemap.html` that routes to `HtmlSiteMapController`
- implement a `HtmlSiteMapController` that uses a XSLT transform to massage the xml into a suitable html format

This was trivially implementable and did the job, but was kind of crude, as you lose a lot of information in the xml format that is present when traversing the site hierarchy. And did I mention learning XSLT? :hankey:

**Comment by marisks** [comment]
Instead of creating an XSLT support, it would be better to decouple sitemap model from XML generation.
I would refactor it by separating XML generation and traversing the site:

create site tree model - classes for tree nodes with all data needed for sitemap

traverse the site and create a site tree

create XML renderer for sitemap.xml

Anyone who would like to implement something else then could use the API to build the tree and create output for any other format - page, JSON API etc.

For now, we do not have the need for such feature, but if you could provide a PR, it would be great.

**Comment by fatso83** [comment]
Since I have left [my employer at the time of the issue](https://github.com/makingwaves) I don't have a use for this anymore, but other should of course be free to reopen given a need.
