### ISSUE TITLE
Possible Cross Site Request Forgery (CSRF) in AdminManageSitemap.aspx

### ISSUE THREAD

**Issue by prochnowc** [Geta/SEO.Sitemaps#54]
Our VA testers found that the AdminManageSitemap.aspx page is vulnerable to CSRF attacks.

**Comment by frederikvig** [comment]
Thanks for reporting this. Will take a look after vacation this week.

**Comment by frederikvig** [comment]
Fixed in version 1.6.4

**Comment by prochnowc** [comment]
Thanks for fixing this issue!

**Comment by larswp** [comment]
The admin tool is behind login, how can it be vulnerable to CSRF attacks?
Anyway now it does not work for me because the AntiForgery.Validate(); throws an exception :(

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.Mvc.HttpAntiForgeryException (0x80004005): The anti-forgery token could not be decrypted. If this application is hosted by a Web Farm or cluster, ensure that all machines are running the same version of ASP.NET Web Pages and that the <machineKey> configuration specifies explicit encryption and validation keys. AutoGenerate cannot be used in a cluster.
   at System.Web.Helpers.AntiXsrf.AntiForgeryTokenSerializer.Deserialize(String serializedToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at Geta.SEO.Sitemaps.Modules.Geta.SEO.Sitemaps.AdminManageSitemap.OnInit(EventArgs e)
